version: "3.8"
services:
  zsh:
    build:
     context: .
     dockerfile: Dockerfile.ubuntu
    container_name: workstation
    hostname: workstation
    stdin_open: true
    tty: true
    ports:
      - "8000:8000" 
      - "3000:3000"
      - "9090:9090"
      - "9229:9229"
    volumes:
      - Workspace:/root/Workspace
      - ~/.ssh/id_rsa:/tmp/id_rsa
      - ./hyperion.priv.gpg:/tmp/hyperion.priv.gpg
      - ./id_rsa_hyperion:/tmp/id_rsa_hyperion
    environment:
    - DISPLAY=192.168.1.132:0.0  
    #- DISPLAY=172.21.240.1:0.0
volumes:
  Workspace:
    external: true
