version: "3.8"
services:
  bash:
    build: .
    # entrypoint: /bin/bash
    container_name: workstation
    hostname: workstation
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9229:9229"
    volumes:
      - Workspace:/root/Workspace
      - ~\.ssh\id_rsa:/tmp/id_rsa
      - .\hyperion.priv:/tmp/hyperion.priv
    environment:
    - DISPLAY=192.168.0.22:0.0
volumes:
  Workspace:
    external: true
