version: '3'
services:
  coder:
    build: .
    entrypoint: 
      - dumb-init
      - code-server
      - --host
      - 0.0.0.0
      - /workspace
      - --auth 
      - none
    ports:
      - "1313"
      - "8080:8080"
    volumes:
      - ..:/workspace
